name: Deploy Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Git 基础配置（可按需保留）
      - name: Git Configuration
        run: |
          git config --global core.quotePath false
          git config --global core.autocrlf false
          git config --global core.safecrlf true
          git config --global core.ignorecase false

      # 3️⃣ 安装 Node（18 LTS）并启用 npm 缓存
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm            # 自动缓存 ~/.npm

      # 4️⃣ 安装依赖
      - name: Install dependencies
        run: npm ci             # 严格依赖 package-lock.json

      # 5️⃣ 构建产物
      - name: Build
        run: npm run build      # 使用 package.json 中的 build 脚本

      # 6️⃣ 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist